require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# We don't use MFA
Gemspec/RequireMFA:
  Enabled: false

# This file is in a different namespace for both lib and spec
# This is because otherwise we would get a filename conflict
RSpec/FilePath:
  Exclude:
    - spec/site_prism/all_there_spec.rb

# The format of this allows the specs to flow a bit better
RSpec/MessageSpies:
  EnforcedStyle: receive

# See: https://github.com/rubocop-hq/rubocop/issues/5953
# Bug in the way rubocop uses this specific cop
Style/AccessModifierDeclarations:
  Enabled: false

# This is a "better" style used in the codebase
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

# This is a style used in the codebase to reduce diff deltas
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

# This is a style used in the codebase to reduce diff deltas
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
