require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

# Allow a longer linelength in SitePrism and ignore Gherkin definitions
Layout/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^Given'
    - '^When'
    - '^Then'

# These two will always break the metric. Should be added to rubocop-rspec
Metrics/BlockLength:
  Exclude:
    - './spec/**/*_spec.rb'
    - 'site_prism.gemspec'

# This rule isn't valid for shared contexts
RSpec/ContextWording:
  Exclude:
    - 'spec/support/shared_context/**.rb'

# The format of this allows the specs to flow a bit better
RSpec/MessageSpies:
  EnforcedStyle: receive

# See: https://github.com/rubocop-hq/rubocop/issues/5953
# Bug in the way rubocop uses this specific cop
Style/AccessModifierDeclarations:
  Enabled: false

# This is a "better" style used in the codebase
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

# This is a style used in the codebase to reduce diff deltas
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

# This is a style used in the codebase to reduce diff deltas
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
