require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

# We don't use MFA
Gemspec/RequireMFA:
  Enabled: false

# This file is in a different namespace for both lib and spec
# This is because otherwise we would get a filename conflict
RSpec/FilePath:
  Exclude:
    - spec/site_prism/all_there_spec.rb

# The format of this allows the specs to flow a bit better
RSpec/MessageSpies:
  EnforcedStyle: receive
