inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^Given'
    - '^When'
    - '^Then'

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

BlockLength:
  Exclude:
    - './spec/**/*_spec.rb'
    - 'site_prism.gemspec'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
