inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^Given'
    - '^When'
    - '^Then'

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Metrics/BlockLength:
  Exclude:
    - './spec/**/*_spec.rb'
    - 'site_prism.gemspec'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

# See: https://github.com/rubocop-hq/rubocop/issues/5953
# Bug in the way rubocop uses this specific cop
Style/AccessModifierDeclarations:
  Enabled: false

# The format of this allows the specs to flow a bit better
RSpec/MessageSpies:
  EnforcedStyle: receive
