language: ruby
sudo: required
dist: xenial

rvm:
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - Gemfile

before_install:
  - gem install bundler -v '> 2'

script:
  - bundle exec rake

branches:
  only:
    - main
