language: ruby
sudo: required
dist: xenial

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

env:
  - browser=firefox

gemfile:
  - Gemfile

script:
  - gem uninstall bundler
  - gem install bundler -v '< 2'
  - bundle exec rake

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
