---
name: build
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7']
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: '2.1.4'
          bundler-cache: true
      - run: bundle exec rake rspec
      - run: bundle exec rake rubocop
